### PR TITLE
Add initial commit

### PR DESCRIPTION
**Pull request by 0romos**
- Added type hints to improve code clarity and type safety.
- Enhanced the `get_version`, `parse_requirements`, and `add_mim_extension` functions with better docstrings.
- Improved error handling and warnings for file operations.
- Cleaned up the parsing logic for requirements files.
- Made the setup script more maintainable and easier to understand.

Changes include:
- Refactoring of `parse_requirements` to handle versioning and platform-specific dependencies more effectively.
- Updated `add_mim_extension` to handle file operations with clearer logic.
- Ensured compatibility with both Windows and non-Windows systems.

### CODE REVIEW

**Comment by rawalkhirodkar** [comment]
PR makes minimal changes to pose setup.py (install) script.
Closing in favor of keeping minimal code history.

**Comment by 0romos** [comment]
The code is kinda a mess, better to have fixed and optimize code, rather than just wanting to have minimal code history, Picking production code is better than just picking minimal code history with a messy and unstable code.

**Comment by rawalkhirodkar** [comment]
Any optimizations to the functional code is welcome! The existing PR modified a single file (pose/setup.py).

**Comment by 0romos** [comment]
Brother will all due respect, all code matters. You can't have one part being dogshit and the other being somewhat okay...

**Pull request closed without merging**
